### ISSUE TITLE
Gulp error - Unhandled 'error' event

### ISSUE THREAD

**Issue by mmcardle** [Axelrod-Python/DjAxelrod#15]
getting this error with the latest code

```
(virt-axel)v53-0a0df045:DjAxelrod mm$ gulp
[08:16:32] Using gulpfile ~/dev/DjAxelrod/gulpfile.js
[08:16:32] Starting 'sass'...
[08:16:32] Starting 'scripts'...
[08:16:32] Starting 'csv'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: File not found with singular glob
    at Glob.<anonymous> (/Users/mm/dev/DjAxelrod/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/index.js:34:30)
    at Glob.EventEmitter.emit (events.js:95:17)
    at Glob._finish (/Users/mm/dev/DjAxelrod/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:171:8)
    at done (/Users/mm/dev/DjAxelrod/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:158:12)
    at Glob._processSimple2 (/Users/mm/dev/DjAxelrod/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:647:12)
    at /Users/mm/dev/DjAxelrod/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:635:10
    at Glob._stat2 (/Users/mm/dev/DjAxelrod/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:731:12)
    at lstatcb_ (/Users/mm/dev/DjAxelrod/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:723:12)
    at RES (/Users/mm/dev/DjAxelrod/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/inflight/inflight.js:23:14)
    at f (/Users/mm/dev/DjAxelrod/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/once/once.js:17:25)
```

**Comment by mmcardle** [comment]
run 

```
bower install
```
